# 异常处理

异常是被程序抛出的一个对象，它表示在程序中出现了一个错误。

**传统的错误处理**

* 终止程序
* 返回错误值
* 返回合法值
* 调用错误处理函数



## 抛出异常

```c++
// 当 h() 函数抛出异常时，已构造 string 按 "DDD" "CCC" "BBB" 的次序依次销毁。
// 控制线程没有到达 "EEE"
// "AAA" 不受影响
void f()
{
	string name {"AAA"};
	try{
		string s = "BBB";
		g();
	}
	catch(My_error){
		//...
	}
}

void g()
{
    string s = "CCC";
    h();
}

void h()
{
    string s1 = "DDD";
    throw My_error{};
    string s2 = "EEE";
}
```

**noexcept 函数**  
有一些函数永远不会抛出异常，可以把它声明成 noexcept 的。

```c++
double compute(double) noexcept;
```



## 捕获异常

```c++
void func()
{
	try{
		throw A{};
	}
	catch(B){
	}
}
```

当满足下述条件之一时，系统会调用异常处理程序：

* A 和 B 类型相同
* A 是 B 的无歧义的公有基类
* A 和 B 都是指针类型，并且它们所指的类型满足前两条之一
* A 是引用类型，并且它所用的类型满足前两条之一

**重新抛出**

```c++
void func()
{
	try{
		// 可能抛出异常
	}
    catch(exception error){
        if(能够处理异常){
            处理异常;
            return;
        }
        else{
            完成一部分;
            throw
        }
    }
}
```

**捕获每个异常**

```c++
void m()
{
	try{
		执行操作;
	}
	catch(...){
		处理每一个异常;
		throw;
	}
}
```

**捕获多个异常**

```c++
void func()
{
	try{
		执行操作;
	}
	catch(std::ios_base::failure){
		处理异常
	}
	catch(std::exception e){
		处理异常
	}
	catch(...){
		处理异常;
	}
}
```

**异常与线程**

如果不希望整个程序因线程中的一个错误而终止执行，就必须捕获全部错误并且以某种方式把它们报告给程序中对线程执行结果感兴趣的部分。

可以用标准库函数 current_exception() 把某一线程的异常传递给另一线程的处理程序。

```c++
try{
	执行操作
}
catch(...){
	prom.set_exception(current_exception());
}
```

